name: CI Build for angular
on: [push, pull_request]
jobs:
  build:
    if: ${{github.repository == 'devonfw/jump-the-queue'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build
        run: |
          cd angular
          yarn install
          npm run build
          npm run test -- --watch=false --browsers=ChromeHeadless
